# Generated by Django 5.2.7 on 2025-11-02 15:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('contact_last_name', models.CharField(max_length=60)),
                ('contact_first_name', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=60)),
                ('primary_phone_number', models.CharField(max_length=20, unique=True)),
                ('secondary_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.CharField(max_length=100, unique=True)),
                ('fax_address', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'db_table': 'suppliers',
                'ordering': ['company_name'],
                'indexes': [models.Index(fields=['company_name'], name='suppliers_company_2938da_idx'), models.Index(fields=['address'], name='suppliers_address_1d32c9_idx'), models.Index(fields=['zip_code'], name='suppliers_zip_cod_7a964d_idx'), models.Index(fields=['city'], name='suppliers_city_dfbf0c_idx'), models.Index(fields=['country'], name='suppliers_country_8cb8cf_idx'), models.Index(fields=['city', 'zip_code'], name='suppliers_city_ca58ab_idx'), models.Index(fields=['contact_last_name'], name='suppliers_contact_a66660_idx'), models.Index(fields=['contact_first_name'], name='suppliers_contact_d68741_idx'), models.Index(fields=['contact_first_name', 'contact_last_name'], name='suppliers_contact_fdd506_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('unit_buy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_buy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.supplier')),
            ],
            options={
                'verbose_name': 'Product',
                'db_table': 'products',
                'ordering': ['product_id'],
                'indexes': [models.Index(fields=['category'], name='products_categor_fce6e6_idx'), models.Index(fields=['description'], name='products_descrip_507bd1_idx'), models.Index(fields=['location'], name='products_locatio_fffa51_idx'), models.Index(fields=['qty'], name='products_qty_ed7394_idx')],
            },
        ),
    ]
