# Generated by Django 5.2.7 on 2025-11-02 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('expected_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qty_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Inventory',
                'db_table': 'inventory',
                'ordering': ['inventory_id'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=60)),
                ('update_description', models.TextField()),
                ('movement_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Log',
                'db_table': 'logs',
                'ordering': ['-update_date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.IntegerField(unique=True)),
                ('code', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField()),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('expected_delivery_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=60)),
                ('order_comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'db_table': 'orders',
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=30)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Order Item',
                'db_table': 'order_items',
                'ordering': ['order_item_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'User'},
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['min_qty'], name='products_min_qty_6caaea_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['max_qty'], name='products_max_qty_71b63e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['unit_buy'], name='products_unit_bu_d5fbee_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['total_buy'], name='products_total_b_eaba18_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['unit_sell'], name='products_unit_se_3bc4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['total_sell'], name='products_total_s_ed13e2_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['title'], name='suppliers_title_a942bc_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['secondary_phone_number'], name='suppliers_seconda_95a828_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name'], name='users_first_n_0c5a67_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name'], name='users_last_na_5e9a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name', 'last_name'], name='users_first_n_de8b69_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.product'),
        ),
        migrations.AddField(
            model_name='log',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.product'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.supplier'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.product'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['expected_qty'], name='inventory_expecte_ccc920_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['actual_qty'], name='inventory_actual__bcf7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['qty_difference'], name='inventory_qty_dif_2c9153_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['update_date'], name='logs_update__9f156d_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['type'], name='logs_type_f14e78_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['update_description'], name='logs_update__e49fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['movement_qty'], name='logs_movemen_d636b6_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['client'], name='logs_client_0e3fda_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['project'], name='logs_project_781b24_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['code'], name='orders_code_5b9ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['create_date'], name='orders_create__944723_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['sent_date'], name='orders_sent_da_e6657d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['expected_delivery_date'], name='orders_expecte_4311c5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['closing_date'], name='orders_closing_bd9c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_comment'], name='orders_order_c_0ff1dd_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['unit'], name='order_items_unit_8f3067_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['qty'], name='order_items_qty_d82e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['unit_cost'], name='order_items_unit_co_937a46_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['total_cost'], name='order_items_total_c_d9e2d4_idx'),
        ),
    ]
